export const event = [
  {
    evendId: 'event01',
    eventTitle: '(제 1회) 베노프 체육대회⛹🏻‍♀️',
    eventImg: process.env.PUBLIC_URL + '/images/now_event_01.jpg',
    eventThumbnail: process.env.PUBLIC_URL + '/images/now_event_01_thumbnail.jpg',
    eventDate: '2025-07-25 ~ 2025-09-23',
    eventCategory: 'now',
  },
  {
    evendId: 'event02',
    eventTitle: '베노프 X 지그재그 뷰티 페스타🎡',
    eventImg: process.env.PUBLIC_URL + '/images/now_event_02.jpg',
    eventThumbnail: process.env.PUBLIC_URL + '/images/now_event_02_thumbnail.jpg',
    eventDate: '2025-07-25 ~ 2025-09-23',
    eventCategory: 'now',
  },
  {
    evendId: 'event03',
    eventTitle: '2025년 베노프 멤버십 안내',
    eventImg: process.env.PUBLIC_URL + '/images/now_event_03.jpg',
    eventThumbnail: process.env.PUBLIC_URL + '/images/now_event_03_thumbnail.jpg',
    eventDate: '2025-07-25 ~ 2025-09-23',
    eventCategory: 'now',
  },
  {
    evendId: 'event04',
    eventTitle: '단백질바 Light 런칭기념 EVENT',
    eventImg: process.env.PUBLIC_URL + '/images/past_event_01.jpg',
    eventThumbnail: process.env.PUBLIC_URL + '/images/past_event_01_thumbnail.jpg',
    eventDate: '2025-07-25 ~ 2025-09-23',
    eventCategory: 'past',
  },
  {
    evendId: 'event05',
    eventTitle: '⛅설프라이즈 1월 이벤트⛅',
    eventImg: process.env.PUBLIC_URL + '/images/past_event_02.jpg',
    eventThumbnail: process.env.PUBLIC_URL + '/images/past_event_02_thumbnail.jpg',
    eventDate: '2025-07-25 ~ 2025-09-23',
    eventCategory: 'past',
  },
  {
    evendId: 'event06',
    eventTitle: '🏆2024 베노프 연말결산🏆',
    eventImg: process.env.PUBLIC_URL + '/images/past_event_03.jpg',
    eventThumbnail: process.env.PUBLIC_URL + '/images/past_event_03_thumbnail.jpg',
    eventDate: '2025-07-25 ~ 2025-09-23',
    eventCategory: 'past',
  },
  {
    evendId: 'event07',
    eventTitle: '🎥 베노프 숏포터즈 3기 모집 🎥',
    eventImg: process.env.PUBLIC_URL + '/images/past_event_04.jpg',
    eventThumbnail: process.env.PUBLIC_URL + '/images/past_event_04_thumbnail.jpg',
    eventDate: '2025-07-25 ~ 2025-09-23',
    eventCategory: 'past',
  },
  {
    evendId: 'event08',
    eventTitle: '💥2024 베노프 블랙프라이데이💥',
    eventImg: process.env.PUBLIC_URL + '/images/past_event_05.jpg',
    eventThumbnail: process.env.PUBLIC_URL + '/images/past_event_05_thumbnail.jpg',
    eventDate: '2025-07-25 ~ 2025-09-23',
    eventCategory: 'past',
  },
]